spring:
    profiles:
    active:
    - dev
 ---
spring:
    profiles: dev
    application:
        name:wscloud-config-dev
---
spring:
    profiles: test
    application:
        name:wscloud-config-test